<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'arii_joc.treegrid' shared service.

return $this->services['arii_joc.treegrid'] = new \Arii\JOCBundle\Service\AriiTreeGrid();
