<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'arii.repository.connection' shared service.

return $this->services['arii.repository.connection'] = new \Arii\CoreBundle\Entity\Connection('AriiCoreBundle:Connection');
