<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'arii_core.session' shared service.

return $this->services['arii_core.session'] = new \Arii\CoreBundle\Service\AriiSession(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load('getSessionService.php')) && false ?: '_'}, $this, ${($_ = isset($this->services['arii_core.db']) ? $this->services['arii_core.db'] : $this->load('getAriiCore_DbService.php')) && false ?: '_'});
