<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'arii_joc.state' shared service.

return $this->services['arii_joc.state'] = new \Arii\JOCBundle\Service\AriiState(${($_ = isset($this->services['arii_core.db']) ? $this->services['arii_core.db'] : $this->load('getAriiCore_DbService.php')) && false ?: '_'}, ${($_ = isset($this->services['arii_core.sql']) ? $this->services['arii_core.sql'] : $this->load('getAriiCore_SqlService.php')) && false ?: '_'}, ${($_ = isset($this->services['arii_core.date']) ? $this->services['arii_core.date'] : $this->load('getAriiCore_DateService.php')) && false ?: '_'});
