<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'arii_core.db' shared service.

return $this->services['arii_core.db'] = new \Arii\CoreBundle\Service\AriiDB('mysqli', '127.0.0.1', 3306, 'arii', 'root', NULL);
