<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'arii_core.doc' shared service.

return $this->services['arii_core.doc'] = new \Arii\CoreBundle\Service\AriiDoc(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'}, 'C:/Program Files/Java/jre1.8.0_144', '/home/arii/Symfony/vendor/ditaa', 'D:/Apps/Arii_NP2023/graphviz-2.38/release/bin/dot.exe');
