<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'arii_core.sos' shared service.

return $this->services['arii_core.sos'] = new \Arii\CoreBundle\Service\AriiSOS(${($_ = isset($this->services['arii_core.audit']) ? $this->services['arii_core.audit'] : $this->load('getAriiCore_AuditService.php')) && false ?: '_'}, ${($_ = isset($this->services['arii_core.log']) ? $this->services['arii_core.log'] : $this->load('getAriiCore_LogService.php')) && false ?: '_'});
