<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'arii_jid.sos' shared service.

return $this->services['arii_jid.sos'] = new \Arii\JIDBundle\Service\AriiSOS(${($_ = isset($this->services['arii_core.session']) ? $this->services['arii_core.session'] : $this->load('getAriiCore_SessionService.php')) && false ?: '_'}, ${($_ = isset($this->services['arii_core.dhtmlx']) ? $this->services['arii_core.dhtmlx'] : $this->load('getAriiCore_DhtmlxService.php')) && false ?: '_'}, ${($_ = isset($this->services['arii_core.sql']) ? $this->services['arii_core.sql'] : $this->load('getAriiCore_SqlService.php')) && false ?: '_'}, ${($_ = isset($this->services['arii_core.audit']) ? $this->services['arii_core.audit'] : $this->load('getAriiCore_AuditService.php')) && false ?: '_'}, ${($_ = isset($this->services['arii_core.log']) ? $this->services['arii_core.log'] : $this->load('getAriiCore_LogService.php')) && false ?: '_'});
