<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'arii_joc.focus' shared service.

return $this->services['arii_joc.focus'] = new \Arii\JOCBundle\Service\AriiFocus(${($_ = isset($this->services['arii_core.tools']) ? $this->services['arii_core.tools'] : $this->load('getAriiCore_ToolsService.php')) && false ?: '_'}, ${($_ = isset($this->services['arii_core.db']) ? $this->services['arii_core.db'] : $this->load('getAriiCore_DbService.php')) && false ?: '_'});
