<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'arii_user.oauth_user_provider' shared service.

return $this->services['arii_user.oauth_user_provider'] = new \Arii\UserBundle\Model\OAuthUserProvider();
