<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\AdminBundle\Command\ExplainAdminCommand' shared service.

return $this->services['Sonata\AdminBundle\Command\ExplainAdminCommand'] = new \Sonata\AdminBundle\Command\ExplainAdminCommand();
