<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.request_matcher.4uqoet0' shared service.

return $this->services['security.request_matcher.4uqoet0'] = new \Symfony\Component\HttpFoundation\RequestMatcher('/(public)/');
