<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.core.date.moment_format_converter' shared service.

return $this->services['sonata.core.date.moment_format_converter'] = new \Sonata\Form\Date\MomentFormatConverter();
