<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.templating' shared service.

return $this->services['sonata.templating'] = new \Sonata\BlockBundle\Templating\TwigEngine(${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.templating.name_parser']) ? $this->services['sonata.templating.name_parser'] : ($this->services['sonata.templating.name_parser'] = new \Sonata\BlockBundle\Templating\TemplateNameParser(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'}))) && false ?: '_'}, ${($_ = isset($this->services['sonata.templating.locator']) ? $this->services['sonata.templating.locator'] : $this->load('getSonata_Templating_LocatorService.php')) && false ?: '_'});
