<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.core.form.type.boolean_legacy' shared service.

return $this->services['sonata.core.form.type.boolean_legacy'] = new \Sonata\CoreBundle\Form\Type\BooleanType();
