arii_GVZ_index:
    path:  /
    defaults: { _controller: AriiGraphvizBundle:Default:index }

arii_GVZ_readme:
    path:  /readme
    defaults: { _controller: AriiGraphvizBundle:Default:readme }

xml_GVZ_toolbar:
    path:  /toolbar.xml
    defaults: { _controller: AriiGraphvizBundle:Default:toolbar }

xml_GVZ_legend:
    path:  /legend.xml
    defaults: { _controller: AriiGraphvizBundle:Default:legend }
    
json_GVZ_ribbon:
    path:  /ribbon.json
    defaults: { _controller: AriiGraphvizBundle:Default:ribbon }

txt_GVZ_file:
    path:  /file
    defaults: { _controller: AriiGraphvizBundle:Default:file }
    
arii_GVZ_generate:
    path:  /generate
    defaults: { _controller: AriiGraphvizBundle:Graphviz:generate }

arii_GVZ_generate_config:
    path:  /generate_config
    defaults: { _controller: AriiGraphvizBundle:Graphviz:config }

arii_GVZ_dropzone:
    path:  /dropzone
    defaults: { _controller: AriiGraphvizBundle:Dropzone:index }

arii_GVZ_upload:
    path:  /upload
    defaults: { _controller: AriiGraphvizBundle:Dropzone:upload }
    
xml_GVZ_tree:
    path:  /tree.xml
    defaults: { _controller: AriiGraphvizBundle:Folders:tree }

xml_GVZ_tree_remote:
    path:  /remote/tree.xml
    defaults: { _controller: AriiGraphvizBundle:Folders:tree, path: remote }



arii_GVZ_audit:
    path:  /audit
    defaults: { _controller: AriiGraphvizBundle:Audit:index }

arii_GVZ_audit_generate:
    path:  /audit/generate
    defaults: { _controller: AriiGraphvizBundle:Audit:generate }

json_GVZ_audit_ribbon:
    path:  /audit/ribbon.json
    defaults: { _controller: AriiGraphvizBundle:Audit:ribbon }

xml_GVZ_audit_comments:
    path:  /audit/comments.xml
    defaults: { _controller: AriiGraphvizBundle:Audit:comments }

xml_GVZ_audit_toolbar:
    path:  /audit/toolbar.xml
    defaults: { _controller: AriiGraphvizBundle:Audit:toolbar }

xml_GVZ_audit_menu:
    path:  /audit/menu.xml
    defaults: { _controller: AriiGraphvizBundle:Audit:menu }

