parameters:
#    arii_graphviz.example.class: Arii\GraphvizBundle\Example

services:
#    arii_graphviz.example:
#        class: %arii_graphviz.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
