parameters:
#    arii_core.example.class: Arii\CoreBundle\Example
      
services:
#    arii_core.example:
#        class: %arii_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
        
services: 
    arii_locale.locale_listener:
        class: Arii\CoreBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
            
    core.twig.core_extension:
        class: Arii\CoreBundle\Twig\CoreExtension
        arguments: ["%locale%"]
        tags:
            - { name: twig.extension }

    arii.repository.connection:
        class: Arii\CoreBundle\Entity\Connection
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AriiCoreBundle:Connection']
        
    arii_core.portal:
        class: Arii\CoreBundle\Service\AriiPortal
        arguments: ["@arii_core.session", "@security.authorization_checker", "@translator", "@router" ]

    arii_core.sql:
        class: Arii\CoreBundle\Service\AriiSQL
        arguments: ["@arii_core.session" ]

    arii_core.date:
        class: Arii\CoreBundle\Service\AriiDate
        arguments: ["@arii_core.session", "@translator"]

    arii_core.session:
        public: true
        class: Arii\CoreBundle\Service\AriiSession
        arguments: ["@session","@service_container","@arii_core.db"]

    arii_core.dhtmlx:
        class: Arii\CoreBundle\Service\AriiDHTMLX
        arguments: [ "@arii_core.session" ]

    arii_core.audit:
        class: Arii\CoreBundle\Service\AriiAudit
        arguments: ["@arii_core.session","@fos_user.user_manager","@doctrine.orm.default_entity_manager"]
        
    arii_core.sos:
        class: Arii\CoreBundle\Service\AriiSOS
        arguments: ["@arii_core.audit","@arii_core.log"]

    arii_core.db:
        class: Arii\CoreBundle\Service\AriiDB
        arguments: [ %database_driver%, %database_host%, %database_port%, %database_name%, %database_user%, %database_password% ]
    
    arii_core.log:
        class: Arii\CoreBundle\Service\AriiLog
        arguments: [ "@doctrine.orm.default_entity_manager","@arii_core.session" ]

    arii_core.message:
        class: Arii\CoreBundle\Service\AriiMessage
        arguments: [ "@doctrine.orm.default_entity_manager" ]

    arii_core.tools:
        class: Arii\CoreBundle\Service\AriiTools
        arguments: [ "@arii_core.session", %workspace% ]
        
    arii_core.files:
        class: Arii\CoreBundle\Service\AriiFiles
        arguments: [ "@arii_core.session", %workspace% ]

    arii_core.folder:
        class: Arii\CoreBundle\Service\AriiFolder
        arguments: [ "@arii_core.session" ]

    arii_core.cron:
        class: Arii\CoreBundle\Service\AriiCron
        arguments: [ "@arii_core.session" ]

    arii_core.doc:
        class: Arii\CoreBundle\Service\AriiDoc
        arguments: ["@request_stack", %java%, %ditaa%, %graphviz_dot% ]

    arii_core.exec:
        class: Arii\CoreBundle\Service\AriiExec
        arguments: [ "@arii_core.session", %workspace%, "@arii_core.db", "@arii_core.sql", "@arii_core.audit", "@arii_core.log" ]
