# --------------------------------------------------------------------------
# Partie public
# --------------------------------------------------------------------------
nagios_JID_jobs:
    path:  /jobs
    defaults: { _controller: AriiJIDBundle:Nagios:jobs }
