parameters:
#    arii_jid.example.class: Arii\JIDBundle\Example

services:
#    arii_jid.example:
#        class: %arii_jid.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    jid.twig.jid_extension:
        class: Arii\JIDBundle\Twig\JIDExtension
        tags:
            - { name: twig.extension }

    arii_jid.sos:
        class: Arii\JIDBundle\Service\AriiSOS
        arguments: [ "@arii_core.session", "@arii_core.dhtmlx", "@arii_core.sql","@arii_core.audit","@arii_core.log"]

    arii_jid.history:
        class: Arii\JIDBundle\Service\AriiHistory
        arguments: [ "@arii_core.dhtmlx", "@arii_core.sql", "@arii_core.date", "@arii_core.tools"]

    arii_jid.graphviz:
        class: Arii\JIDBundle\Service\AriiGraphviz
        arguments: [  "@arii_core.tools", "@arii_core.dhtmlx", "@arii_core.sql"  ]

        