arii_Admin_index:
    path:  /
    defaults: { _controller: AriiAdminBundle:Default:index }

arii_Admin_readme:
    path:  /readme
    defaults: { _controller: AriiAdminBundle:Default:readme }

arii_Admin_network:
    path:  /network
    defaults: { _controller: AriiAdminBundle:Default:network }

json_Admin_ribbon:
    path:  /ribbon.json
    defaults: { _controller: AriiAdminBundle:Default:ribbon }

xml_Admin_toolbar:
    path:  /toolbar.xml
    defaults: { _controller: AriiAdminBundle:Toolbar:global }

#============================================================
# Categories
#------------------------------------------------------------
arii_Admin_categories:
    path:  /categories
    defaults: { _controller: AriiAdminBundle:Categories:index}
    
xml_Admin_categories_grid:
    path:  /categories/grid.xml
    defaults: { _controller: AriiAdminBundle:Categories:grid}
    
xml_Admin_categories_tree:
    path:  /categories/tree.xml
    defaults: { _controller: AriiAdminBundle:Categories:tree}

xml_Admin_categories_select:
    path:  /categories/select.xml
    defaults: { _controller: AriiAdminBundle:Categories:select }

#------------------------------------------------------------
# Categorie
#------------------------------------------------------------
xml_Admin_category_toolbar:
    path:  /category/toolbar.xml
    defaults: { _controller: AriiAdminBundle:Category:toolbar}

xml_Admin_category_form:
    path:  /category/form.xml
    defaults: { _controller: AriiAdminBundle:Category:form}

xml_Admin_category_form_structure:
    path:  /category/form_structure.xml
    defaults: { _controller: AriiAdminBundle:Category:form_structure}

xml_Admin_category_save:
    path:  /category/save.xml
    defaults: { _controller: AriiAdminBundle:Category:save}

xml_Admin_category_delete:
    path:  /category/delete.xml
    defaults: { _controller: AriiAdminBundle:Category:delete}

xml_Admin_category_dragdrop:
    path:  /category/dragdrop.xml
    defaults: { _controller: AriiAdminBundle:Category:dragdrop}

#============================================================
# Connections
#------------------------------------------------------------
arii_Admin_connections:
    path:  /connections
    defaults: { _controller: AriiAdminBundle:Connections:index}
    
xml_Admin_connections_grid:
    path:  /connections/grid.xml
    defaults: { _controller: AriiAdminBundle:Connections:grid}
    
xml_Admin_connections_menu:
    path:  /connections/menu.xml
    defaults: { _controller: AriiAdminBundle:Connections:menu}

#------------------------------------------------------------
# Connection
#------------------------------------------------------------
xml_Admin_connection_toolbar:
    path:  /connection/toolbar.xml
    defaults: { _controller: AriiAdminBundle:Connection:toolbar}

xml_Admin_connection_form:
    path:  /connection/form.xml
    defaults: { _controller: AriiAdminBundle:Connection:form}

xml_Admin_connection_form_structure:
    path:  /connection/form_structure.xml
    defaults: { _controller: AriiAdminBundle:Connection:form_structure}

xml_Admin_connection_save:
    path:  /connection/save.xml
    defaults: { _controller: AriiAdminBundle:Connection:save}

xml_Admin_connection_delete:
    path:  /connection/delete.xml
    defaults: { _controller: AriiAdminBundle:Connection:delete}

#============================================================
# Repositories
#------------------------------------------------------------
arii_Admin_repositories:
    path:  /repositories
    defaults: { _controller: AriiAdminBundle:Repositories:index}

xml_Admin_repositories_grid:
    path:  /repositories/grid.xml
    defaults: { _controller: AriiAdminBundle:Repositories:grid}

xml_Admin_repositories_menu:
    path:  /repositories/menu.xml
    defaults: { _controller: AriiAdminBundle:Repositories:menu}

xml_Admin_repositories_connections:
    path:  /repositories/connections.xml
    defaults: { _controller: AriiAdminBundle:Repositories:connections}
    
#------------------------------------------------------------
# Repository
#------------------------------------------------------------
xml_Admin_repository_toolbar:
    path:  /repository/toolbar.xml
    defaults: { _controller: AriiAdminBundle:Repository:toolbar}

xml_Admin_repository_form:
    path:  /repository/form.xml
    defaults: { _controller: AriiAdminBundle:Repository:form}
    
xml_Admin_repository_save:
    path:  /repository/save
    defaults: { _controller: AriiAdminBundle:Repository:save}

xml_Admin_repository_delete:
    path:  /repository/delete
    defaults: { _controller: AriiAdminBundle:Repository:delete}
    
xml_Admin_repository_edit:
    path:  /repository/edit
    defaults: { _controller: AriiAdminBundle:Repository:edit}
#============================================================
# Sites
#------------------------------------------------------------
arii_Admin_sites:
    path:  /sites
    defaults: { _controller: AriiAdminBundle:Sites:index}

xml_Admin_sites_grid:
    path:  /sites/grid.xml
    defaults: { _controller: AriiAdminBundle:Sites:grid}

xml_Admin_sites_show:
    path:  /sites/show.xml
    defaults: { _controller: AriiAdminBundle:Sites:show}

xml_Admin_sites_menu:
    path:  /sites/menu.xml
    defaults: { _controller: AriiAdminBundle:Sites:menu}

xml_Admin_sites_connections:
    path:  /sites/connections.xml
    defaults: { _controller: AriiAdminBundle:Sites:connections}
#------------------------------------------------------------
# Repository
#------------------------------------------------------------
xml_Admin_site_toolbar:
    path:  /site/toolbar.xml
    defaults: { _controller: AriiAdminBundle:Site:toolbar}

xml_Admin_site_form:
    path:  /site/form.xml
    defaults: { _controller: AriiAdminBundle:Site:form}
    
xml_Admin_site_save:
    path:  /site/save
    defaults: { _controller: AriiAdminBundle:Site:save}

xml_Admin_site_delete:
    path:  /site/delete
    defaults: { _controller: AriiAdminBundle:Site:delete}

#============================================================
# Nodes
#------------------------------------------------------------
arii_Admin_nodes:
    path:  /nodes
    defaults: { _controller: AriiAdminBundle:Nodes:index}

xml_Admin_nodes_treegrid:
    path:  /nodes/treegrid.xml
    defaults: { _controller: AriiAdminBundle:Nodes:treegrid}

xml_Admin_nodes_menu:
    path:  /nodes/menu.xml
    defaults: { _controller: AriiAdminBundle:Nodes:menu}

#============================================================
# Spoolers
#------------------------------------------------------------
arii_Admin_spoolers:
    path:  /spoolers
    defaults: { _controller: AriiAdminBundle:Spoolers:index}

xml_Admin_spoolers_treegrid:
    path:  /spoolers/treegrid.xml
    defaults: { _controller: AriiAdminBundle:Spoolers:treegrid}

xml_Admin_spoolers_menu:
    path:  /spoolers/menu.xml
    defaults: { _controller: AriiAdminBundle:Spoolers:menu}

#------------------------------------------------------------
# Spooler
#------------------------------------------------------------
xml_Admin_spooler_toolbar:
    path:  /spoolers/toolbar.xml
    defaults: { _controller: AriiAdminBundle:Spooler:toolbar}

xml_Admin_spooler_supervisors_select:
    path:  /spooler/supervisors/select.xml
    defaults: { _controller: AriiAdminBundle:Spooler:supervisors}

xml_Admin_spooler_sites_select:
    path:  /spooler/sites/select.xml
    defaults: { _controller: AriiAdminBundle:Spooler:sites}

xml_Admin_spooler_transfer_select:
    path:  /spooler/transfer/select.xml
    defaults: { _controller: AriiAdminBundle:Spooler:transfer}

xml_Admin_spooler_mail_select:
    path:  /spooler/mail/select.xml
    defaults: { _controller: AriiAdminBundle:Spooler:mail}

xml_Admin_spooler_backup_select:
    path:  /spooler/backup/select.xml
    defaults: { _controller: AriiAdminBundle:Spooler:backup }
    
xml_Admin_spooler_repositories_select:
    path:  /spooler/repositories/select.xml
    defaults: { _controller: AriiAdminBundle:Spooler:repositories}

xml_Admin_spooler_http_select:
    path:  /spooler/http/select.xml
    defaults: { _controller: AriiAdminBundle:Spooler:http}

xml_Admin_spooler_form:
    path:  /spooler/form.xml
    defaults: { _controller: AriiAdminBundle:Spooler:form}

xml_Admin_spooler_save:
    path:  /spooler/save.xml
    defaults: { _controller: AriiAdminBundle:Spooler:save}

xml_Admin_spooler_delete:
    path:  /spooler/delete.xml
    defaults: { _controller: AriiAdminBundle:Spooler:delete}

#============================================================
# Teams
#------------------------------------------------------------
arii_Admin_teams:
    path:  /teams
    defaults: { _controller: AriiAdminBundle:Teams:index}

xml_Admin_teams_menu:
    path:  /teams/menu.xml
    defaults: { _controller: AriiAdminBundle:Teams:menu}

xml_Admin_teams_tree:
    path:  /teams/tree.xml
    defaults: { _controller: AriiAdminBundle:Teams:tree}

xml_Admin_teams_select:
    path:  /teams/select.xml
    defaults: { _controller: AriiAdminBundle:Teams:select}
#------------------------------------------------------------
# Team
#------------------------------------------------------------
xml_Admin_team_add:
    path:  /team/add
    defaults: { _controller: AriiAdminBundle:Team:add}

xml_Admin_team_form:
    path:  /team/form.xml
    defaults: { _controller: AriiAdminBundle:Team:form}

xml_Admin_team_toolbar:
    path:  /team/toolbar.xml
    defaults: { _controller: AriiAdminBundle:Team:toolbar}

xml_Admin_team_save:
    path:  /team/save.xml
    defaults: { _controller: AriiAdminBundle:Team:save}

xml_Admin_team_delete:
    path:  /team/delete.xml
    defaults: { _controller: AriiAdminBundle:Team:delete}

#------------------------------------------------------------
# TeamFilter
#------------------------------------------------------------
xml_Admin_teamfilter_menu:
    path:  /teamfilter/menu.xml
    defaults: { _controller: AriiAdminBundle:TeamFilter:menu}
    
xml_Admin_teamfilter_toolbar:
    path:  /teamfilter/toolbar.xml
    defaults: { _controller: AriiAdminBundle:TeamFilter:toolbar}

arii_Admin_teamfilter_processor:
    path:  /teamfilter/processor
    defaults: { _controller: AriiAdminBundle:TeamFilter:processor}


arii_Admin_team_attachFilter:
    path:  /team/attach_filter
    defaults: { _controller: AriiAdminBundle:User:attach_filter}

arii_Admin_team_attachFilter_toolbar:
    path:  /team/attach_filter_toolbar
    defaults: { _controller: AriiAdminBundle:User:attach_filter_toolbar}

arii_Admin_team_ajax_addFilter:
    path:  /team/ajax_addFilter
    defaults: { _controller: AriiAdminBundle:User:ajax_addFilter}

arii_Admin_team_editFilter:
    path:  /team/edit_filter
    defaults: { _controller: AriiAdminBundle:User:edit_filter}

arii_Admin_team_deleteFilter:
    path:  /team/delete_filter
    defaults: { _controller: AriiAdminBundle:User:delete_filter}

arii_Admin_team_saveFilter:
    path:  /team/save_filter
    defaults: { _controller: AriiAdminBundle:User:save_filter}


#============================================================
# Users
#------------------------------------------------------------
arii_Admin_users:
    path:  /users
    defaults: { _controller: AriiAdminBundle:Users:index }

xml_Admin_users_grid:
    path:  /users/grid.xml
    defaults: { _controller: AriiAdminBundle:Users:grid }
    
xml_Admin_users_menu:
    path:  /users/menu.xml
    defaults: { _controller: AriiAdminBundle:Users:menu}

xml_Admin_users_toolbar:
    path:  /users/toolbar.xml
    defaults: { _controller: AriiAdminBundle:Users:toolbar}

#------------------------------------------------------------
# User
#------------------------------------------------------------
arii_Admin_user:
    path:  /user
    defaults: { _controller: AriiAdminBundle:User:index}

xml_Admin_user_toolbar:
    path:  /user/toolbar.xml
    defaults: { _controller: AriiAdminBundle:User:toolbar}

xml_Admin_user_form:
    path:  /user/form.xml
    defaults: { _controller: AriiAdminBundle:User:form}

xml_Admin_user_save:
    path:  /user/save.xml
    defaults: { _controller: AriiAdminBundle:User:save}

xml_Admin_user_drag:
    path:  /user/drag.xml
    defaults: { _controller: AriiAdminBundle:User:drag}

#============================================================

arii_Admin_user_select_team:
    path:  /user/select_team
    defaults: { _controller: AriiAdminBundle:User:select_team}

arii_Admin_user_select_enterprise:
    path:  /user/select_enterprise
    defaults: { _controller: AriiAdminBundle:User:select_enterprise}

arii_Admin_user_delete:
    path:  /user/delete
    defaults: { _controller: AriiAdminBundle:User:delete}

arii_Admin_user_userProcessor:
    path:  /user/userProcessor
    defaults: { _controller: AriiAdminBundle:User:userProcessor}


#============================================================
# Rights
#------------------------------------------------------------
xml_Admin_rights_toolbar:
    path:  /rights/toolbar.xml
    defaults: { _controller: AriiAdminBundle:Rights:toolbar }

xml_Admin_rights:
    path:  /rights/list.xml
    defaults: { _controller: AriiAdminBundle:Rights:rights }
    
xml_Admin_team_rights:
    path:  /team/rights.xml
    defaults: { _controller: AriiAdminBundle:Rights:team_rights }

xml_Admin_rights_form:
    path:  /rights/form.xml
    defaults: { _controller: AriiAdminBundle:Rights:form }
    
xml_Admin_rights_grid:
    path:  /rights/grid.xml
    defaults: { _controller: AriiAdminBundle:Rights:grid }

xml_Admin_rights_menu:
    path:  /rights/menu.xml
    defaults: { _controller: AriiAdminBundle:Rights:menu }

#============================================================
# Zones
#------------------------------------------------------------
arii_Admin_zones:
    path:  /zones
    defaults: { _controller: AriiAdminBundle:Zones:index}

xml_Admin_zones_tree:
    path:  /zones/tree.xml
    defaults: { _controller: AriiAdminBundle:Zones:tree}

xml_Admin_zones_select:
    path:  /zones/select.xml
    defaults: { _controller: AriiAdminBundle:Zones:select }
