parameters:
#    arii_admin.example.class: Arii\AdminBundle\Example

services:
#    arii_admin.example:
#        class: %arii_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
