<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTuogwhc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTuogwhc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTuogwhc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTuogwhc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTuogwhc\appProdProjectContainer([
    'container.build_hash' => 'Tuogwhc',
    'container.build_id' => 'fb20025f',
    'container.build_time' => 1554823229,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTuogwhc');
