# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_SYSADMIN,ROLE_OPERATOR,ROLE_DEVELOPPER]
        ROLE_MANAGER:     [ROLE_USER,ROLE_OPERATOR,ROLE_DEVELOPPER]
        ROLE_OPERATOR:    [ROLE_USER]
        ROLE_DEVELOPPER:  [ROLE_USER]
        ROLE_SYSADMIN:    [ROLE_ALLOWED_TO_SWITCH,ROLE_DEVELOPPER]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, in_memory]
 
        in_memory:
            memory: 
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username


    firewalls:
        login:
            pattern:   ^/(login$|register|resetting|sync_state)  # Les adresses de ces pages sont login, register
            security: false

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
            pattern:  ^/(user)/
            security: false

        public:
            pattern:  /(public)/
            security: false

        main:
            pattern: ^/
            form_login:
                #username_parameter: 'login[username]'
                #password_parameter: 'login[password]'
                #csrf_parameter:     'login[_token]'
                #csrf_provider:      form.csrf_provider

                use_referer:  true
                default_target_path: arii_Home_index

            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
                # invalidate_session: true

            remember_me:
                secret: %secret%
                remember_me_parameter: 'login[remember_me]'

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
